fix(bug): build failed with tag "oss"
```
cmd/drone-server/inject_store.go:63:19: too many arguments in call to db.Connect

    have (string, string, int)
    want (string, string)
```

introduced by https://github.com/drone/drone/pull/3089

Signed-off-by: guessi <guessi@gmail.com>